version: '3'
services:
  wikijs:
    image: requarks/wiki:latest
    restart: always
    ports:
      - "10101:3000"
    environment:
      - DB_TYPE=sqlite
      - DB_FILEPATH=/var/wiki/data/wiki.db
    volumes:
      - ./data:/var/wiki/data
